name = "MultiLayerNFRHT"
uuid = "1437eaf2-1009-11e9-29b3-179d2bd09029"
authors = ["Olivier Merchiers <omerchiers@gmail.com>"]
version = "0.1.0"

[deps]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
MyPhysicalConstants = "03bd0ab0-1009-11e9-287f-65bf770f7c3e"
OpticalProperties = "8b3727e0-1008-11e9-018f-895af1a7be12"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
